import { useEffect, useState } from 'react';
import { fetchCrmLeads } from '../services/api';
import './CrmLeadsPage.css';

const STATUS_STYLES = {
  new: 'status-new',
  contacted: 'status-contacted',
  converted: 'status-converted',
};

export default function CrmLeadsPage() {
  const [leads, setLeads] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchCrmLeads()
      .then(setLeads)
      .catch(() => setError('Failed to load CRM leads.'))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="leads-page">
        <div className="leads-loading">Loading CRM leads...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="leads-page">
        <div className="leads-error">{error}</div>
      </div>
    );
  }

  return (
    <div className="leads-page">
      <div className="leads-header">
        <h2>CRM Leads</h2>
        <p className="leads-subtitle">All leads generated by the voice AI agent</p>
        <span className="leads-count">{leads.length} lead{leads.length !== 1 ? 's' : ''}</span>
      </div>

      {leads.length === 0 ? (
        <div className="leads-empty">
          <p>No CRM leads yet. Book an appointment via the voice agent to create a lead.</p>
        </div>
      ) : (
        <div className="leads-table-wrapper">
          <table className="leads-table">
            <thead>
              <tr>
                <th>Patient</th>
                <th>Source</th>
                <th>Status</th>
                <th>Interaction Summary</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              {leads.map((lead) => (
                <tr key={lead.id}>
                  <td className="lead-patient">{lead.patient?.name || '—'}</td>
                  <td>
                    <span className="lead-source">{lead.source}</span>
                  </td>
                  <td>
                    <span className={`lead-status ${STATUS_STYLES[lead.status] || ''}`}>
                      {lead.status}
                    </span>
                  </td>
                  <td className="lead-summary">{lead.interaction_summary}</td>
                  <td className="lead-date">
                    {new Date(lead.created_at).toLocaleDateString('en-US', {
                      month: 'short',
                      day: 'numeric',
                      year: 'numeric',
                      hour: '2-digit',
                      minute: '2-digit',
                    })}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
